### PR TITLE
James rider toggle button

### PR DESCRIPTION
**Pull request by JamesEllenstein**
Adds button to toggle rider to UserTable and tests to ensure mutation and coverage security

# Storybook
* [Before](https://ucsb-cs156-s23.github.io/proj-gauchoride-s23-5pm-1/storybook/?path=/story/components-users-userstable--three-users)
* [After](https://ucsb-cs156-s23.github.io/proj-gauchoride-s23-5pm-1/prs/25/storybook/?path=/story/components-users-userstable--three-users)

### CODE REVIEW

**Review by cmfisher606 — APPROVED** [review]
Lgtm! :)

**Review by cmfisher606 — DISMISSED** [review]
lgtm

**Review by pconrad — DISMISSED** [review]
I added storybook before/after to the description (next time I'll ask the team to do that.)

It revealed that there might be something missing in the fixtures that this storybook entry is based on; notice that the rider column is undefined.

https://ucsb-cs156-s23.github.io/proj-gauchoride-s23-5pm-1/prs/25/storybook/?path=/story/components-users-userstable--three-users

Could you take a look and see if the fixtures need to be updated for that field?

**Review by zpr-ucsb — APPROVED** [review]
looks good

**Pull request merged**
